<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            
            [
                'reg_no' => 'FOC1000',
                'user_name' => 'Deepika Fernando',
                'email' => 'super000@gmail.com',
                'password' => Hash::make('1234'),
                'dep_id' => 2,
                'is_student' => false,
                'is_management' => false,
                'is_super_admin' => true,
            ],
            [
                'reg_no' => 'KDU001',
                'user_name' => 'Head Quartes',
                'email' => 'HQ@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 4,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU002',
                'user_name' => 'IT Division',
                'email' => 'itivision@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 5,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU003',
                'user_name' => 'Log Office',
                'email' => 'log@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 6,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU004',
                'user_name' => 'FDSS',
                'email' => 'fdss@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 7,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU005',
                'user_name' => 'Cadet Mess',
                'email' => 'cadetmess@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 8,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU006',
                'user_name' => 'Publication',
                'email' => 'publication@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 9,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU007',
                'user_name' => 'Sport Division',
                'email' => 'sport@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 10,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU008',
                'user_name' => 'Technical Support Office',
                'email' => 'tso@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 11,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU009',
                'user_name' => 'Help Desk',
                'email' => 'helpdesk@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 14,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU010',
                'user_name' => 'Enlistment',
                'email' => 'enlistment@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 15,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU011',
                'user_name' => 'Library',
                'email' => 'library@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 12,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU012',
                'user_name' => 'Account Section',
                'email' => 'account@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 13,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            /////////////////////////////////////////
            [
                'reg_no' => 'KDU013',
                'user_name' => 'AR_FDSS',
                'email' => 'arfdss@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 14,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU014',
                'user_name' => 'AR_FMSH',
                'email' => 'arfmsh@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 15,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU015',
                'user_name' => 'AR_FOM',
                'email' => 'arfom@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 16,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU016',
                'user_name' => 'AR_FOE',
                'email' => 'arfoe@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 17,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU017',
                'user_name' => 'AR_FOL',
                'email' => 'arfol@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 18,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU018',
                'user_name' => 'AR_Alied_Health_Science',
                'email' => 'arfahs@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 19,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU019',
                'user_name' => 'AR_FOC',
                'email' => 'arcomputing@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 20,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU020',
                'user_name' => 'AR_FBAS',
                'email' => 'arfbas@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 21,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU021',
                'user_name' => 'AR_FOT',
                'email' => 'arfot@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 22,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU022',
                'user_name' => 'AR_FOCJ',
                'email' => 'arfocj@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 23,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
            [
                'reg_no' => 'KDU023',
                'user_name' => 'AR_FBESS',
                'email' => 'arfbess@gmail.com',
                'password' => Hash::make('password'),
                'dep_id' => 24,
                'is_student' => false,
                'is_management' => true,
                'is_super_admin' => false,
            ],
        ]);
    }
}
