<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Application PDF</title>
    <style>
    /* Add your PDF styles here */
    body {
        font-family: DejaVu Sans, sans-serif;
        padding: 20px;
    }

    .header {
        text-align: center;
        margin-bottom: 20px;
    }

    .details {
        margin-bottom: 10px;
    }

    .details strong {
        display: inline-block;
        width: 150px;
    }
    </style>
</head>

<body>
    <div class="header">
        <h1>Application Details</h1>
    </div>

    <div class="details">
        <strong>Application ID:</strong> {{ $application->id }}
    </div>
    <div class="details">
        <strong>User Name:</strong> {{ $application->user->user_name }}
    </div>
    <div class="details">
        <strong>Registration Number:</strong> {{ $application->user->reg_no }}
    </div>
    <div class="details">
        <strong>Status:</strong> {{ $status->status }}
    </div>
    <div class="details">
        <strong>PDF Reason/Info:</strong> {{ $pdf_reason }}
    </div>
    <div class="details">
        <strong>Generated By:</strong> {{ $user->name }}
    </div>
    <div class="details">
        <strong>Generated At:</strong> {{ now()->format('Y-m-d H:i:s') }}
    </div>
</body>

</html>